version: "3"
services:
    bot:
        build:
            context: .
        env_file: ".env-local"
        container_name: "robo-noodle"
        volumes:
          - .:/opt/docroot
        networks: 
          - backend

networks:
    backend:
        driver: bridge
        driver_opts:
            com.docker.network.driver.mtu: 1400